In [3]:
import numpy as np

In [5]:
print(np.arange(5))

[0 1 2 3 4]


In [8]:
print(np.linspace(0, 5, 10, endpoint=True))

print(np.linspace(0, 5, 10, endpoint=False))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [10]:
print(np.zeros(5))
print(np.ones(5))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [13]:
print(np.ones((5,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [15]:
print(np.random.randn(5))

[-0.32755896  0.97335931  0.68790999  0.03923513 -0.30319476]


In [16]:
print(np.random.randn(5,2))

[[-0.4268907  -1.12797358]
 [ 0.98548618 -1.01456383]
 [-0.22132515 -0.52724103]
 [-0.84252309  0.7088025 ]
 [ 1.450047    1.03128202]]


In [17]:
x = np.arange(10)
print(x[2:4])

[2 3]


In [19]:
print(x[-1])

9


In [20]:
print(x[0:8:2])

[0 2 4 6]


In [21]:
print(x[4:2:-1])

[4 3]


In [22]:
print(x[:4])

[0 1 2 3]


In [23]:
print(x[:999])

[0 1 2 3 4 5 6 7 8 9]


In [24]:
print(x[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [27]:
x = np.arange(5)
y = np.ones(5)

print(x+2*y)

[2. 3. 4. 5. 6.]


In [28]:
x = np.random.randn(5)
y = np.ones(5)

print(np.dot(x,y))

-2.7510763971924854


In [30]:
x = np.random.randn(5,3)
y = np.ones((3,2))

print(np.dot(x,y))

[[-2.77914163 -2.77914163]
 [-1.26699765 -1.26699765]
 [ 0.80728062  0.80728062]
 [ 0.98862079  0.98862079]
 [-1.68251956 -1.68251956]]


In [31]:
x = np.arange(10)
print(x < 5)

[ True  True  True  True  True False False False False False]


In [33]:
y = np.ones(10)
print(x < y)

[ True False False False False False False False False False]


In [41]:
from scipy.spatial import distance

print(distance.euclidean([0, 0], [3,4]))
print(distance.sqeuclidean([0, 0], [3, 4]))
print(distance.cityblock([0, 0], [3, 4]))
print(distance.chebyshev([0, 0], [3, 4]))

5.0
25.0
7
4


In [43]:
print(distance.cosine([67, 0], [89, 0]))
print(distance.cosine([67, 0], [0, 89]))

0
1.0


In [44]:
x = np.random.randn(5)
print(x)
x.sort()
print(x)

[ 1.21380473 -0.92644057 -0.10361544  1.54798528 -0.92972755]
[-0.92972755 -0.92644057 -0.10361544  1.21380473  1.54798528]


In [45]:
x = np.random.randn(5)
print(x)
ind = np.argsort(x)
print(ind)
print(x[ind])


[ 1.65517694 -0.38867771  0.33209081  1.0897318   0.39650025]
[1 2 4 3 0]
[-0.38867771  0.33209081  0.39650025  1.0897318   1.65517694]
